# Generated by Django 5.0.3 on 2024-04-14 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_remove_usertheme_id_remove_usertoken_id_and_more'),
        ('main', '0006_delete_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertheme',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.register'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.register'),
        ),
    ]
