# Generated by Django 5.0.3 on 2024-04-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_alter_usertheme_user_alter_usertoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
