# Generated by Django 5.0.3 on 2024-04-02 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Вход в систему',
                'verbose_name_plural': 'Входы в систему',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('login', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(limit_value=6, message='Логин должен содержать не менее 6 символов')], verbose_name='Логин')),
                ('name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2, 'Имя должно содержать не менее 2 символов')], verbose_name='Имя')),
                ('surname', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2, 'Фамилия должна содержать не менее 2 символов')], verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Некорректный формат email')], verbose_name='Email')),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=8, message='Пароль должен содержать не менее 8 символов'), django.core.validators.RegexValidator(message='Пароль должен содержать хотя бы одну цифру, одну прописную и одну строчную букву, один специальный символ', regex='^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+]).{8,}$')], verbose_name='Пароль')),
                ('confirm_password', models.CharField(max_length=20, verbose_name='Подтверждение пароля')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=6, verbose_name='Пол')),
                ('age_confirmation', models.BooleanField(default=False, verbose_name='Мне 18 лет')),
                ('rules_acceptance', models.BooleanField(default=False, verbose_name='Принимаю правила')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
            },
        ),
    ]
