# Generated by Django 5.0.3 on 2024-04-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_login_recaptcha_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='recaptcha_response',
        ),
    ]
