# Generated by Django 5.0.3 on 2024-04-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_usertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
